/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/CubeGuyCharacter.glb -o src/components/content/canvas/maps/player/Man.jsx 
*/

import { useGLTF } from "@react-three/drei";
import { usePlayer } from "./hooks/usePlayer";
import { TextBoard } from "../structures/ground/3dUIs/TextBoard";

export function Player({ player, position, modelIndex: mIdx }) {
  const modelIndex = mIdx ?? player.selectedCharacterGlbNameIndex;
  const {
    me,
    playerRef,
    nicknameRef,
    memoizedPosition,
    playerId,
    nodes,
    materials,
  } = usePlayer({
    player,
    position,
    modelIndex,
  });
  return (
    <>
      {me && (
        <TextBoard
          ref={nicknameRef}
          text={`${player?.nickname}[${player?.jobPosition}]`}
        />
      )}
      <group
        ref={playerRef}
        position={memoizedPosition}
        name={playerId ?? ""}
        dispose={null}
      >
        <group name="Root_Scene">
          <group name="RootNode">
            <group
              name="CharacterArmature"
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <primitive object={nodes.Root} />
            </group>
            <skinnedMesh
              name="Character"
              castShadow
              receiveShadow
              geometry={nodes.Character.geometry}
              material={
                modelIndex === 1 ? materials["Atlas.001"] : materials.Atlas
              }
              skeleton={nodes.Character.skeleton}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/CubeGuyCharacter.glb");
